import test from 'node:test';
import assert from 'node:assert/strict';
import {executeBatch,closeDue,historySettlement,recordEntry,eligible} from '../../supabase/functions/_shared/plan_b_live_cycle.mjs';
const NOW=Date.parse('2026-08-31T00:01:00Z');
function signal(id,symbol='AVAX'){return {id,symbol,side:'long',strategy_id:'b_core_sparse_stage26',status:'active',signal_price:10,leverage:symbol==='ICP'?5:3,hold_hours:symbol==='ICP'?2:13,confirmed_at:new Date(NOW-60000).toISOString(),entry_deadline:new Date(NOW+240000).toISOString(),expires_at:new Date(NOW-1).toISOString(),dispatched_at:null};}
function fixture({enabled=true,test_mode=false,signals=[signal(1),signal(2,'ICP')]}={}){
 const tables={plan_b_trading_state:[{id:'singleton',strategy_id:'b_core_sparse_stage26',enabled,test_mode}],plan_b_signals:signals,plan_b_execution_intents:[],plan_b_real_trades:[]};
 const calls=[],rpcCalls=[];
 const sb={from(name){assert(name.startsWith('plan_b_'));let filters=[],action='select',value,single=false;const q={
  select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},gt(k,v){filters.push(r=>r[k]>v);return q},is(k,v){filters.push(r=>(r[k]??null)===v);return q},
  in(k,v){filters.push(r=>v.includes(r[k]));return q},not(k,op,v){filters.push(r=>op==='is'?r[k]!=null:!v.slice(1,-1).split(',').includes(r[k]));return q},order(){return q},
  single(){single=true;return q},maybeSingle(){single=true;return q},update(v){action='update';value=v;return q},upsert(v){action='upsert';value=v;return q},
  then(resolve){let rows=tables[name].filter(r=>filters.every(f=>f(r)));if(action==='update')rows.forEach(r=>Object.assign(r,value));if(action==='upsert'){let row=tables[name].find(r=>r.signal_id===value.signal_id);if(row)Object.assign(row,value);else tables[name].push({id:tables[name].length+1,...value});rows=[value];}resolve({data:single?rows[0]??null:rows.map(r=>({...r,plan_b_signals:tables.plan_b_signals.find(s=>s.id===r.signal_id)})),error:null});}
 };return q;},rpc(name,args){rpcCalls.push({name,args});if(name==='plan_b_reserve_intents'){const total=args.p_items.reduce((s,x)=>s+x.reserved_usd,0);assert(total<=142.500001);for(const i of args.p_items){const s=signals.find(s=>s.id===i.signal_id);tables.plan_b_execution_intents.push({id:i.signal_id,...i,symbol:s.symbol,side:s.side,client_order_id:'pb26-'+s.id,status:'reserved',close_attempt:0});}return Promise.resolve({data:true});}if(name==='plan_b_claim_intent'){const row=tables.plan_b_execution_intents.find(r=>r.client_order_id===args.p_id);row.status='submitted';return Promise.resolve({data:true});}throw Error(name);}};
 let position=0;
 const bx={verifyConfiguration:async()=>({maxLongLeverage:5,maxShortLeverage:5}),lookup:async()=>({status:'not_found'}),
  async read(path){calls.push(path);if(path.includes('positions'))return position?[{symbol:'AVAX-USDT',positionSide:'LONG',positionAmt:position}]:[];if(path.includes('balance'))return [{asset:'USDT',balance:150,equity:150,availableMargin:150}];if(path.includes('premium'))return {markPrice:10};if(path.includes('positionHistory'))return [];if(path.includes('contracts'))return ['AVAX','ICP'].map(symbol=>({symbol:symbol+'-USDT',quantityPrecision:2,tradeMinQuantity:.01,tradeMinUSDT:1,apiStateOpen:true,apiStateClose:true,status:1,maxLongLeverage:5}));throw Error(path);},
  async submit(o){calls.push({submit:o});if(o.close)position=0;return {status:'filled',terminal:true,quantity:o.quantity,price:10,orderId:'9223372036854775806'};}};
 return {sb,bx,tables,calls,rpcCalls,now:()=>NOW,setPosition:q=>position=q};
}
test('actual execution batches two signals inside one $142.50 reservation',async()=>{const f=fixture();await executeBatch(f);assert.equal(f.rpcCalls.filter(x=>x.name==='plan_b_reserve_intents').length,1);assert.equal(f.tables.plan_b_real_trades.length,2);assert.equal(f.calls.filter(x=>x.submit).length,2);});
test('OFF and TEST never touch exchange or write fake real trades',async()=>{for(const cfg of [{enabled:false},{test_mode:true}]){const f=fixture(cfg);await executeBatch(f);assert.equal(f.calls.length,0);assert.equal(f.tables.plan_b_real_trades.length,0);}});
test('leverage verification failure sends no orders',async()=>{const f=fixture();f.bx.verifyConfiguration=async()=>{throw Error('mismatch')};await assert.rejects(()=>executeBatch(f));assert.equal(f.calls.filter(x=>x.submit).length,0);});
test('submission timeout retains collateral and does not mark rejection',async()=>{const f=fixture({signals:[signal(1)]});f.bx.submit=async()=>{throw Error('timeout')};await executeBatch(f);assert.equal(f.tables.plan_b_execution_intents[0].status,'unknown');assert(f.tables.plan_b_execution_intents[0].reserved_usd>0);assert.equal(f.tables.plan_b_real_trades.length,0);});
test('expired signals cannot reach reservation',async()=>{const f=fixture({signals:[{...signal(1),entry_deadline:new Date(NOW-1).toISOString()}]});await executeBatch(f);assert.equal(f.rpcCalls.length,0);assert.equal(eligible({...signal(1),confirmed_at:new Date(NOW+1).toISOString()},NOW),false);});
function closingFixture(){const f=fixture({enabled:false,signals:[signal(1)]});f.tables.plan_b_real_trades.push({id:1,signal_id:1,symbol:'AVAX',side:'long',status:'open',quantity:2,entry_price:10,bingx_order_id:'entry-1',client_order_id:'pb26-1',filled_at:new Date(NOW-3600000).toISOString(),created_at:new Date(NOW-3600000).toISOString()});f.tables.plan_b_execution_intents.push({id:1,signal_id:1,status:'open',close_attempt:0});f.setPosition(2);return f;}
test('OFF still closes verified live position; PnL waits for exchange settlement',async()=>{const f=closingFixture();await closeDue(f);assert.equal(f.calls.filter(x=>x.submit)[0].submit.close,true);assert.equal(f.tables.plan_b_real_trades[0].status,'closed');assert.equal(f.tables.plan_b_real_trades[0].net_pnl_usd,null);});
test('unfilled close never changes trade to closed',async()=>{const f=closingFixture();f.bx.submit=async()=>({status:'unknown'});await closeDue(f);assert.equal(f.tables.plan_b_real_trades[0].status,'open');assert.equal(f.tables.plan_b_execution_intents[0].status,'closing');});
test('no exchange order id cannot be synthetically closed',async()=>{const f=closingFixture();f.tables.plan_b_real_trades[0].bingx_order_id=null;await closeDue(f);assert.equal(f.tables.plan_b_real_trades[0].status,'open');assert.equal(f.calls.filter(x=>x.submit).length,0);});
test('gross-only and ambiguous history never masquerade as net PnL',()=>{const t={symbol:'AVAX',side:'long',filled_at:new Date(NOW-60000).toISOString()};const p={symbol:'AVAX-USDT',positionSide:'LONG',openTime:NOW-60000,closeTime:NOW,avgClosePrice:11,profit:2};assert.equal(historySettlement([p],t),null);assert.equal(historySettlement([{...p,netProfit:1.5}],t).net_pnl_usd,1.5);assert.equal(historySettlement([{...p,netProfit:1.5},{...p,netProfit:1.5}],t),null);});
