const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync('supabase/functions/bingx-order-execute/index.ts','utf8');
const closeSource=source.slice(source.indexOf('async function handleClose('),source.indexOf('// 손절/익절이 안 걸려있는',source.indexOf('async function handleClose(')));
async function simulate(remaining){let reconciled=0;const context=vm.createContext({Response,Number,Math,Error,Promise,console,API_KEY:'fixture',SECRET_KEY:'fixture',setTimeout:fn=>fn(),db:async()=>[{id:1,quantity:2,bingx_symbol:'BTC-USDT',side:'long'}],getContract:async()=>({quantityPrecision:3}),roundDown:v=>v,reconcileOpenTrades:async()=>{reconciled++},fetchSigned:async(a,b,method,path)=>path.endsWith('/positions')?[{symbol:'BTC-USDT',positionSide:'LONG',positionAmt:remaining}]:path.endsWith('/openOrders')?[]:{}});vm.runInContext(stripTypeScriptTypes(closeSource)+'\nthis.handle=handleClose;',context);const r=await context.handle({id:1});return {body:await r.json(),reconciled};}
test('A accepted close with remaining position is not success',async()=>{const r=await simulate(1);assert.equal(r.body.ok,false);assert.equal(r.reconciled,0);});
test('A zero exchange remainder confirms closure',async()=>{const r=await simulate(0);assert.equal(r.body.closed,true);assert.equal(r.reconciled,1);});
test('A nonfinite remaining quantity fails closed',async()=>{assert.equal((await simulate('bad')).body.ok,false);});
test('A manual same-side remainder blocks automatic close before touching orders',async()=>{const r=await simulate(3);assert.equal(r.body.ok,false);assert.match(r.body.error,/manual position overlap/);assert.equal(r.reconciled,0);});
test('A reconciliation no longer sums symbol income into a trade',()=>{const block=source.slice(source.indexOf('async function reconcileOpenTrades'),source.indexOf('async function handleReprice'));assert(!block.includes('/user/income'));assert(block.includes('netPnl: number | null = null'));});
test('A failed daily rebalance remains retryable; successful boundary commits',()=>{const s=fs.readFileSync('supabase/functions/coin-collector/index.ts','utf8');const start=s.indexOf('const completed=!audit.some'),end=s.indexOf('candidates.hourly_audit=',start);assert(start>0);const block=s.slice(start,end);for(const status of ['close_failed','entry_failed','entry_pending','held','entered','cash']){const c=vm.createContext({audit:[{status}],candidates:{last_mdd30_decision_closed_at:1},forceAnswerRebalance:false,answerDecisionClosedAt:2});vm.runInContext(block,c);assert.equal(c.candidates.last_mdd30_decision_closed_at,['close_failed','entry_failed','entry_pending'].includes(status)?1:2);}});
test('A Stage184 is not blocked by legacy account loss breakers',()=>{const s=fs.readFileSync('supabase/functions/bingx-order-execute/index.ts','utf8');assert.match(s,/if \(!candidateA && dailyNetPnl <= -dailyLossLimitUsd\)/);assert.match(s,/if \(!candidateA && !manualImmediateMdd30 && consecutiveLosses >= maxConsecutiveLosses/);});
test('managed A waits for completed live hourly audit',()=>{const s=fs.readFileSync('supabase/functions/managed-account-executor/index.ts','utf8');assert.match(s,/hourly_audit,status.*='completed'/);assert.match(s,/coin_snapshots where id='live'/);assert.doesNotMatch(s,/last_mdd30_decision_closed_at.*id='latest'/);});
test('A retry_pending decision survives the end of the UTC decision hour',()=>{const s=fs.readFileSync('supabase/functions/coin-collector/index.ts','utf8');assert.match(s,/const retryAnswerDecision=candidates\.hourly_audit\?\.status==="retry_pending"/);assert.match(s,/const newAnswerDecision=forceAnswerRebalance\|\|retryAnswerDecision\|\|/);assert.match(s,/const storedAnswer=forceAnswerRebalance\|\|retryAnswerDecision\?/);assert.match(s,/last_mdd30_decision_closed_at=answerDecisionClosedAt/);});
test('A admission reads persisted signal before freshness validation',()=>{assert(source.indexOf('signal = stored;')<source.indexOf('const admission = aEntryAdmission'));assert(!source.includes('26 * 3600000'));});
test('close retry recognizes an already settled trade without another order',async()=>{const context=vm.createContext({Response,API_KEY:'fixture',SECRET_KEY:'fixture',db:async path=>path.includes('status=eq.closed')?[{id:1}]:[]});vm.runInContext(stripTypeScriptTypes(closeSource)+'\nthis.handle=handleClose;',context);assert.equal((await (await context.handle({id:1})).json()).closed,true);});
