import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {normalizeBOrder,constrainBQuantity,createBExchange} from '../../supabase/functions/_shared/plan_b_exchange.mjs';
// Exercise offline configuration without changing the actual owner-enabled runtime file.
const offlineSource=fs.readFileSync('supabase/functions/_shared/plan_b_exchange.mjs','utf8').replace("import standard from './plan_b_standard.json' with {type:'json'};",'const standard='+fs.readFileSync('supabase/functions/_shared/plan_b_standard.json','utf8')+';').replace("import runtime from './plan_b_runtime.json' with {type:'json'};",'const runtime={live_ready:false};');
const {createBExchange:createOfflineExchange}=await import('data:text/javascript;base64,'+Buffer.from(offlineSource).toString('base64'));
test('live runtime refuses configuration changes without exchange requests',async()=>{let calls=0;const b=createBExchange({apiKey:'fixture',secret:'fixture',configurationAuthorized:()=>true,fetcher:async()=>{calls++;}});await assert.rejects(()=>b.alignLeverage('AVAX'),/locked/);assert.equal(calls,0);});
test('large order IDs preserved and unsafe IDs rejected',()=>{assert.equal(normalizeBOrder({status:'FILLED',executedQty:'2',avgPrice:'3',orderID:'9223372036854775806'}).orderId,'9223372036854775806');assert.throws(()=>normalizeBOrder({orderId:9223372036854775806}));});
test('cancelled partial fill remains a settled nonzero fill, never a rejection',()=>{const fill=normalizeBOrder({status:'CANCELED',executedQty:'1',avgPrice:'3'});assert.equal(fill.status,'filled');assert.equal(fill.terminal,true);assert.equal(normalizeBOrder({status:'NEW',executedQty:'0'}).status,'unknown');});
test('quantity floors and strict contract boundaries',()=>{const c={symbol:'AVAX-USDT',quantityPrecision:2,tradeMinQuantity:.01,tradeMinUSDT:2,apiStateOpen:'true',apiStateClose:'true',status:1,maxLongLeverage:3};const o={symbol:'AVAX',side:'long',quantity:1.239,leverage:3};assert.equal(constrainBQuantity(o,c,10).quantity,1.23);assert.throws(()=>constrainBQuantity({...o,quantity:.001},c,10));assert.throws(()=>constrainBQuantity(o,{...c,maxLongLeverage:2},10));});
test('entry submit blocked before fetch when entry switch is off',async()=>{let calls=0;const b=createBExchange({apiKey:'test',secret:'test',liveAuthorized:()=>false,fetcher:async()=>{calls++;throw Error('must not fetch');}});await assert.rejects(()=>b.submit({plan:'B',symbol:'AVAX',side:'long',clientOrderId:'pb16-test',quantity:1}));assert.equal(calls,0);});
test('rate-limited reads retry at most twice',async()=>{let n=0;const b=createBExchange({apiKey:'test',secret:'test',sleep:async()=>{},fetcher:async()=>({ok:true,text:async()=>JSON.stringify(++n<3?{code:100410}:{code:0,data:[]})})});assert.deepEqual(await b.read('/openApi/swap/v2/user/positions'),[]);assert.equal(n,3);});
test('persistent rate limits terminate after three reads',async()=>{let n=0;const b=createBExchange({apiKey:'test',secret:'test',sleep:async()=>{},fetcher:async()=>{n++;return {ok:true,text:async()=>'{"code":100410}'};}});await assert.rejects(()=>b.read('/openApi/swap/v2/user/positions'));assert.equal(n,3);});
function configMock({positions=[],failWrite=false,authorized=true}={}){const writes=[],lev={longLeverage:20,shortLeverage:20,maxLongLeverage:50,maxShortLeverage:50};const b=createOfflineExchange({apiKey:'test',secret:'test',configurationAuthorized:()=>authorized,sleep:async()=>{},fetcher:async(url,opt)=>{const p=new URL(url).pathname;let data;if(opt.method==='POST'){const q=new URLSearchParams(opt.body);writes.push({path:p,side:q.get('side'),leverage:q.get('leverage')});if(failWrite)throw Error('timeout');lev[q.get('side')==='LONG'?'longLeverage':'shortLeverage']=Number(q.get('leverage'));data={};}else if(p.endsWith('/dual'))data={dualSidePosition:true};else if(p.endsWith('/marginType'))data={marginType:'ISOLATED'};else if(p.endsWith('/leverage'))data=lev;else if(p.endsWith('/positions'))data=positions;else if(p.endsWith('/openOrders'))data={orders:[]};else throw Error(p);return {ok:true,text:async()=>JSON.stringify({code:0,data})};}});return {b,writes};}
test('configuration uses only adopted B leverage and never submits orders',async()=>{const {b,writes}=configMock();const r=await b.alignLeverage('AVAX');assert.deepEqual(r.after,{long:3,short:3});assert.equal(r.orders_submitted,0);assert.equal(writes.length,2);assert.ok(writes.every(w=>w.path.endsWith('/leverage')&&w.leverage==='3'));});
test('configuration refuses unauthorized access and A symbols',async()=>{const {b,writes}=configMock({authorized:false});await assert.rejects(()=>b.alignLeverage('AVAX'));await assert.rejects(()=>b.alignLeverage('BTC'));assert.equal(writes.length,0);});
test('configuration cannot modify an existing position',async()=>{const {b,writes}=configMock({positions:[{positionAmt:'1'}]});await assert.rejects(()=>b.alignLeverage('AVAX'));assert.equal(writes.length,0);});
test('configuration timeout never blindly retries writes',async()=>{const {b,writes}=configMock({failWrite:true});await assert.rejects(()=>b.alignLeverage('AVAX'));assert.equal(writes.length,1);});
