const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync('supabase/functions/bingx-order-execute/index.ts','utf8');
const closeSource=source.slice(source.indexOf('async function handleClose('),source.indexOf('// 손절/익절이 안 걸려있는',source.indexOf('async function handleClose(')));
async function simulate(remaining){let reconciled=0;const context=vm.createContext({Response,Number,Math,Error,Promise,console,API_KEY:'fixture',SECRET_KEY:'fixture',setTimeout:fn=>fn(),db:async()=>[{id:1,quantity:2,bingx_symbol:'BTC-USDT',side:'long'}],getContract:async()=>({quantityPrecision:3}),roundDown:v=>v,reconcileOpenTrades:async()=>{reconciled++},fetchSigned:async(a,b,method,path)=>path.endsWith('/positions')?[{symbol:'BTC-USDT',positionSide:'LONG',positionAmt:remaining}]:path.endsWith('/openOrders')?[]:{}});vm.runInContext(stripTypeScriptTypes(closeSource)+'\nthis.handle=handleClose;',context);const r=await context.handle({id:1});return {body:await r.json(),reconciled};}
test('A accepted close with remaining position is not success',async()=>{const r=await simulate(1);assert.equal(r.body.ok,false);assert.equal(r.reconciled,0);});
test('A zero exchange remainder confirms closure',async()=>{const r=await simulate(0);assert.equal(r.body.closed,true);assert.equal(r.reconciled,1);});
test('A nonfinite remaining quantity fails closed',async()=>{assert.equal((await simulate('bad')).body.ok,false);});
test('A reconciliation no longer sums symbol income into a trade',()=>{const block=source.slice(source.indexOf('async function reconcileOpenTrades'),source.indexOf('async function handleReprice'));assert(!block.includes('/user/income'));assert(block.includes('netPnl: number | null = null'));});
test('A failed daily rebalance remains retryable; successful boundary commits',()=>{const s=fs.readFileSync('supabase/functions/coin-collector/index.ts','utf8');const start=s.indexOf('const completed=!audit.some'),end=s.indexOf('candidates.hourly_audit=',start);assert(start>0);const block=s.slice(start,end);for(const status of ['close_failed','entry_failed','entry_pending','held','entered','cash']){const c=vm.createContext({audit:[{status}],candidates:{last_mdd30_decision_closed_at:1},forceAnswerRebalance:false,closedHourAt:2});vm.runInContext(block,c);assert.equal(c.candidates.last_mdd30_decision_closed_at,['close_failed','entry_failed','entry_pending'].includes(status)?1:2);}});
