import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {stripTypeScriptTypes} from 'node:module';
import {aEntryAdmission,currentADecision,nextADecisionBoundary,completeAClose} from '../../supabase/functions/_shared/a_recovery_policy.mjs';
const boundary=Date.parse('2026-09-15T00:59:59.999Z'), now=boundary+2*3600000;
function fixture(){return {s:{id:1,symbol:'XRP',side:'short',status:'active',signal_type:'answer_mdd30',signal_model_version:'answer_mdd30_stage184_v1',strategy_epoch:'answer_mdd30_stage75_2026_09_08',created_at:'2026-09-15T01:00:01Z',entry_metrics:{strategy_config:{base_exposure_multiplier:.15}}},c:{hourly_audit:{status:'retry_pending',closed_at:new Date(boundary).toISOString(),assets:[{symbol:'XRP',signal_id:1,answer:{side:'short',exposure:.15}}]}}};}
test('legacy orphan has no flag but uses persisted matching daily answer',()=>{const {s,c}=fixture();assert.equal(aEntryAdmission(s,c,now).recovery,true);});
test('exact next UTC decision rejects even recently created old decision',()=>{const {s,c}=fixture();s.entry_metrics.strategy_config.decision_closed_at=c.hourly_audit.closed_at;s.created_at='2026-09-16T00:59:00Z';const next=Date.parse('2026-09-16T01:00:00Z');assert.equal(nextADecisionBoundary(boundary),next);assert.equal(currentADecision(boundary,next-1),true);assert.equal(aEntryAdmission(s,c,next).allowed,false);});
test('future, malformed and previous-day recovery are rejected',()=>{for(const at of [NaN,now+1,boundary-86400000])assert.equal(currentADecision(at,now),false);const {s,c}=fixture();for(const value of ['bad','2026-09-16T01:00:00Z']){s.created_at=value;assert.equal(aEntryAdmission(s,c,now).allowed,false);}});
test('changed side, exposure, ID, version and terminal status cannot recover',()=>{const mutations=[({s})=>s.side='long',({s})=>s.id=2,({s})=>s.status='invalidated',({s})=>s.signal_model_version='old',({c})=>c.hourly_audit.assets[0].answer.exposure=.3,({c})=>c.hourly_audit.status='completed',({c})=>delete c.hourly_audit.assets[0].answer];for(const mutate of mutations){const f=fixture();mutate(f);assert.equal(aEntryAdmission(f.s,f.c,now).allowed,false);}});
test('C freeze and pending close block even a fresh entry',()=>{const {s,c}=fixture();s.created_at=new Date(now).toISOString();c.a_c_controller={freeze_until:new Date(now+1).toISOString()};assert.equal(aEntryAdmission(s,c,now).allowed,false);delete c.a_c_controller;s.entry_metrics.c_close_intent={status:'pending'};assert.equal(aEntryAdmission(s,c,now).allowed,false);});
test('C close failure survives reload and completes only after confirmation',async()=>{let signal={id:1,side:'long',entry_price:100,entry_metrics:{c_close_intent:{status:'pending',trigger_closed_at:boundary}}};let calls=0,writes=0;const deps={now:new Date(now).toISOString(),price:90,close:async()=>++calls>1,patch:async(id,v)=>{writes++;signal={...signal,...v};}};assert.equal((await completeAClose(signal,deps)).pending,true);assert.equal(writes,0);signal=JSON.parse(JSON.stringify(signal));assert.equal((await completeAClose(signal,deps)).closed,true);assert.equal(signal.entry_metrics.c_close_intent.status,'completed');await completeAClose(signal,deps);assert.equal(calls,2);});
test('C ledger patch failure preserves retryable intent',async()=>{const signal={id:1,side:'short',entry_price:100,entry_metrics:{c_close_intent:{status:'pending'}}};await assert.rejects(completeAClose(signal,{now:'x',price:110,close:async()=>true,patch:async()=>{throw Error('DB unavailable');}}));assert.equal(signal.entry_metrics.c_close_intent.status,'pending');});
const collector=fs.readFileSync('supabase/functions/coin-collector/index.ts','utf8');
const cBlock=collector.slice(collector.indexOf('  const cState:any='),collector.indexOf('  active=[...legacyActive,...open()]'));
async function evaluate(valid){const symbols=['BTC','ETH','XRP','TRX','SOL'],state={last_evaluated_closed_at:boundary-3600000};const ctx=vm.createContext({candidates:{a_c_controller:state},commonClosedAt:boundary,ANSWER_ASSETS:symbols,market:Object.fromEntries(symbols.map(s=>[s,{suite_setup:{closed_at:boundary,data_valid:valid,c_returns_168h:valid?Array(168).fill(0):[]}}])),nowIso:'2026-09-15T01:01:00Z',median:()=>0,populationStd:()=>0,correlation:()=>0,open:()=>[]});await vm.runInContext('(async()=>{'+stripTypeScriptTypes(cBlock)+'})()',ctx);return state;}
test('invalid C data retains evaluation boundary; restored data advances it',async()=>{assert.equal((await evaluate(false)).last_evaluated_closed_at,boundary-3600000);assert.equal((await evaluate(true)).last_evaluated_closed_at,boundary);});
test('C persists all targets and freeze before the first exchange call',async()=>{
 const events=[],symbols=['BTC','ETH','XRP','TRX','SOL'],signals=symbols.slice(0,3).map((symbol,i)=>({id:i+1,symbol,side:'long',signal_type:'answer_mdd30',entry_price:100}));
 const ctx=vm.createContext({candidates:{},old:{heartbeat:'previous'},commonClosedAt:boundary,ANSWER_ASSETS:symbols,liveOpenSignalIds:new Set([1,2,3]),market:Object.fromEntries(symbols.map(s=>[s,{suite_setup:{closed_at:boundary,data_valid:true,c_returns_168h:Array(168).fill(-.02)}}])),nowIso:'2026-09-15T01:01:00Z',median:()=>-.02,populationStd:x=>x.length===6?2:1,correlation:()=>.9,open:()=>signals,patchSignal:async(id,body)=>{assert.equal(body.entry_metrics.c_close_intent.status,'pending');events.push('persist '+id);},save:async p=>{assert(p.signal_candidates.a_c_controller.freeze_until);assert.equal(p.heartbeat,'previous');events.push('save freeze');},finishCClose:async s=>{events.push('close '+s.id);return {closed:false,pending:true};}});
 await vm.runInContext('(async()=>{'+stripTypeScriptTypes(cBlock)+'})()',ctx);
 assert.deepEqual(events,['persist 1','persist 2','persist 3','save freeze','close 1','close 2','close 3']);
 assert(signals.every(s=>s.entry_metrics.c_close_intent.status==='pending'));
});
