import {allHistoryPages} from "../_shared/history_pages.mjs";
import {webhookSecret,validWebhookSecret} from "../_shared/telegram_webhook_auth.mjs";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";
import { createHmac } from "node:crypto";
const URL=Deno.env.get("SUPABASE_URL")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,BOT=Deno.env.get("TELEGRAM_BOT_TOKEN")||"",CHAT="6818439075",BINGX_KEY=Deno.env.get("BINGX_API_KEY")||"",BINGX_SECRET=Deno.env.get("BINGX_SECRET_KEY")||"",PB_KEY=Deno.env.get("PLAN_B_BINGX_API_KEY")||"",PB_SECRET=Deno.env.get("PLAN_B_BINGX_SECRET_KEY")||"",COIN_ISSUE_URL="https://minyoullee.github.io/coin-issue-ai/",WEBHOOK_SECRET=Deno.env.get("TELEGRAM_WEBHOOK_SECRET")||"";
const sb=createClient(URL,SERVICE);const keyboard={keyboard:[["🔵 A 현황","🟣 B 현황"],["🔵 A 기록","🟣 B 기록"],["👥 타인 API 연동"],["🔗 대시보드","❓ 도움말"]],resize_keyboard:true,is_persistent:true};
async function tg(method:string,body:any={}){if(!BOT)throw new Error("TELEGRAM_BOT_TOKEN missing");const r=await fetch(`https://api.telegram.org/bot${BOT}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(`Telegram ${j.error_code}: ${j.description}`);return j.result}
async function send(chatId:string,text:string,menu=true){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,...(menu?{reply_markup:keyboard}:{})})}
async function link(chatId:string){return tg("sendMessage",{chat_id:chatId,text:"<b>Coin Issue AI</b>\n실시간 코인 이슈·트레이딩 대시보드",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"🚀 대시보드 열기",url:COIN_ISSUE_URL}]]}})}
function n(v:any,d=2){const x=Number(v);return Number.isFinite(x)?x.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}):"-"}function px(v:any){const x=Number(v);return Number.isFinite(x)?(x<10?n(x,5):n(x,2)):"-"}function sign(p:any){const q={...p,timestamp:Date.now()},s=Object.keys(q).sort().map(k=>`${k}=${q[k]}`).join("&");return `${s}&signature=${createHmac("sha256",BINGX_SECRET).update(s).digest("hex")}`}
async function bx(path:string,p:any={}){const r=await fetch(`https://open-api.bingx.com${path}?${sign(p)}`,{headers:{"X-BX-APIKEY":BINGX_KEY},signal:AbortSignal.timeout(10000)});const j=await r.json();if(Number(j.code)!==0)throw new Error(`BingX ${j.code}: ${j.msg}`);return j.data}
async function pbx(path:string,p:any={}){const q={...p,timestamp:Date.now()},s=Object.keys(q).sort().map(k=>`${k}=${q[k]}`).join("&"),sig=createHmac("sha256",PB_SECRET).update(s).digest("hex"),r=await fetch(`https://open-api.bingx.com${path}?${s}&signature=${sig}`,{headers:{"X-BX-APIKEY":PB_KEY},signal:AbortSignal.timeout(10000)}),j=await r.json();if(Number(j.code)!==0)throw new Error(`BingX B ${j.code}: ${j.msg}`);return j.data}
async function account(){const[a,p]=await Promise.all([bx("/openApi/swap/v3/user/balance",{recvWindow:5000}),bx("/openApi/swap/v2/user/positions",{recvWindow:5000})]);const rows=Array.isArray(a)?a:(Array.isArray(a?.balance)?a.balance:[a?.balance||a||{}]),b=rows.find((x:any)=>String(x?.asset||"").toUpperCase()==="USDT")||rows[0]||{},pr=(Array.isArray(p)?p:(p?.positions||[])).filter((x:any)=>Math.abs(Number(x.positionAmt??x.positionAmount??0))>0);return{balance:+b.balance||0,equity:+b.equity||0,available:+b.availableMargin||0,used:+b.usedMargin||0,upnl:+b.unrealizedProfit||0,positions:pr}}
async function history(id:string){const rows=await allHistoryPages(async(offset,limit)=>{const{data,error}=await sb.from("bingx_trade_history").select("external_id,status,realized_pnl_usd,fee_usd").eq("status","closed").not("realized_pnl_usd","is",null).order("external_id").range(offset,offset+limit-1);if(error)throw error;return data});const pnls=rows.map((x:any)=>Number(x.realized_pnl_usd)).filter(Number.isFinite),wins=pnls.filter((x:number)=>x>0),losses=pnls.filter((x:number)=>x<0),closed=pnls.length,winPnl=wins.reduce((a:number,v:number)=>a+v,0),lossPnl=losses.reduce((a:number,v:number)=>a+v,0),fee=rows.reduce((a:number,x:any)=>a+Math.abs(Number(x.fee_usd)||0),0),net=pnls.reduce((a:number,v:number)=>a+v,0),rate=closed?wins.length/closed*100:0,current=100+net;return send(id,`<b>🔵 A플랜 · BingX 실거래 기록</b>\n\n승률        <b>${n(rate,1)}%</b>\n승리        <b>${wins.length}번  +$${n(winPnl)}</b>\n패배        <b>${losses.length}번  -$${n(Math.abs(lossPnl))}</b>\n\n총 수수료   <b>-$${n(fee)}</b>\n실제 순수익 <b>${net>=0?"+":"-"}$${n(Math.abs(net))}</b>\n실현 기준금 <b>${n(current)} USDT</b> · 시작 $100\n입출금·미실현 제외 · 실제 잔고는 🔵 A 현황`)}
async function pbAccount(){const[a,p]=await Promise.all([pbx("/openApi/swap/v3/user/balance",{recvWindow:5000}),pbx("/openApi/swap/v2/user/positions",{recvWindow:5000})]),rows=Array.isArray(a)?a:(Array.isArray(a?.balance)?a.balance:[a?.balance||a||{}]),b=rows.find((x:any)=>String(x.asset||"").toUpperCase()==="USDT")||rows[0]||{},positions=(Array.isArray(p)?p:(p?.positions||[])).filter((x:any)=>Math.abs(Number(x.positionAmt??x.positionAmount??0))>0);return{balance:+b.balance||0,equity:+b.equity||0,available:+b.availableMargin||0,used:+b.usedMargin||0,upnl:+b.unrealizedProfit||0,positions}}
async function pbHistory(id:string){const{data:s,error}=await sb.rpc("plan_b_history_stats");if(error)throw error;return send(id,`<b>🟣 B플랜 · 공격형 실거래 기록</b>\n\n거래 ${s.closed}회 · 승률 <b>${n(s.win_rate,1)}%</b>\n승리 ${s.wins}번 · 패배 ${s.losses}번\n순수익 <b>$${n(s.total_pnl_usd)}</b>\n수수료 $${n(s.total_fee_usd)}\n시작 기준 <b>$650</b> · 실현 기준금 <b>${n(s.realized_equity_usd)}</b>\n입출금·미실현 제외\n현재 담보금은 🟣 B 잔고에서 확인하세요.`)}
async function managedOverview(id:string){const{data,error}=await sb.from("managed_bingx_accounts").select("id,display_name,assigned_plan,starting_equity_usdt,current_equity_usdt,status,alerts_enabled").order("display_name");if(error)throw error;if(!data?.length)return send(id,"<b>👥 타인 API 연동</b>\n\n아직 연결된 계정이 없습니다.\n실제 BingX API를 받을 때 이름·A/B플랜·시작금액을 등록합니다.");const lines=data.map((x:any)=>`${x.assigned_plan==="A"?"🔵":"🟣"} <b>${String(x.display_name).replace(/[<>&]/g,"")}</b> · ${x.assigned_plan}플랜\n시작 $${n(x.starting_equity_usdt)} · 현재 ${x.current_equity_usdt==null?"연결 대기":"$"+n(x.current_equity_usdt)} · 알림 ${x.alerts_enabled?"ON":"OFF"}`).join("\n\n");const buttons=data.map((x:any)=>[{text:`${x.assigned_plan==="A"?"🔵":"🟣"} ${String(x.display_name).slice(0,40)} 거래내역`,callback_data:`managed:${x.id}`}]);return tg("sendMessage",{chat_id:id,text:`<b>👥 타인 API 연동 · ${data.length}명</b>\n\n${lines}\n\n이 계정들의 자동 거래 알림은 기본 OFF입니다.`,parse_mode:"HTML",reply_markup:{inline_keyboard:buttons}})}
async function managedTrades(id:string,accountId:string){const[{data:a,error:ae},{data:rows,error}]=await Promise.all([sb.from("managed_bingx_accounts").select("display_name,assigned_plan").eq("id",accountId).maybeSingle(),sb.from("managed_bingx_trades").select("symbol,side,status,entry_price,close_price,realized_pnl_usdt,opened_at,closed_at").eq("account_id",accountId).order("created_at",{ascending:false}).limit(20)]);if(ae||error)throw ae||error;if(!a)return send(id,"계정을 찾을 수 없습니다.");if(!rows?.length)return send(id,`<b>${a.assigned_plan==="A"?"🔵":"🟣"} ${String(a.display_name).replace(/[<>&]/g,"")} · 거래내역</b>\n\n아직 기록이 없습니다.`);const lines=rows.map((x:any)=>`${x.symbol} ${String(x.side).toUpperCase()} · ${x.status}\n진입 ${px(x.entry_price)}${x.close_price?" · 청산 "+px(x.close_price):""}${x.realized_pnl_usdt==null?"":` · ${Number(x.realized_pnl_usdt)>=0?"+":""}$${n(x.realized_pnl_usdt)}`}`).join("\n\n");return send(id,`<b>${a.assigned_plan==="A"?"🔵":"🟣"} ${String(a.display_name).replace(/[<>&]/g,"")} · 최근 거래</b>\n\n${lines}`)}
async function answer(id:string,text:string){const t=text.trim();if(t==="/start"||t==="❓ 도움말"||t.toLowerCase()==="help")return send(id,"<b>Coin Issue AI · A/B 독립 운영봇</b>\n\n🔵 <b>A플랜</b> 방어형 · 기존 계정\n🟣 <b>B플랜</b> 공격형 · 별도 계정\n\n잔고·포지션·기록·시스템은 완전히 분리됩니다.");if(t==="🔗 Coin Issue AI"||/코인\s*이슈|coin issue/i.test(t))return link(id);if(t==="🔵 A플랜")return send(id,"<b>🔵 A플랜</b>\nStage75 낙폭방어형 · 기존 BingX 계정/API · 현재 운영 중");if(t==="🟣 B플랜")return send(id,"<b>🟣 B플랜 · 공격형</b>\n기본 AVAX·ICP·BCH·DOGE·UNI + 보조 ALGO·ETH·VET·LINK·DOT·LTC·BNB·ADA\nStage93 · Stage66 + ALGO 개선 + ADA 시간대 반전\n연구 $100 → $6,858,952.97\n5년 모의 복리 +6,858,852.97%\n995회 · 승률 55.68%\n시간봉 평가 최대낙폭 -54.65% / 종료 기준 -46.66%\n보호선은 완료 1시간봉으로 갱신 · 완료 1분봉 이탈 시 청산\n기본·보조 동시 보유 금지 · 청산 확인 후 원 신호 5분 미만 진입\n실거래 성과 기준 $650 · 주문은 실제 Equity·가용 담보 기준\nBinance 기반 연구 · 실거래/미래 성과 보장 아님\nA플랜과 API·계정·신호·기록 완전 분리");
 if(t==="🔗 대시보드")return link(id);
 if(t==="👥 타인 API 연동")return managedOverview(id);
if(t==="🔵 A 현황"||t==="🟣 B 현황"){
 const isB=t==="🟣 B 현황",a=await (isB?pbAccount():account());
 const {data:state,error}=await sb.from(isB?"plan_b_trading_state":"real_trading_state").select("enabled,test_mode").eq("id","singleton").single();if(error)throw error;
 const positions=a.positions.map((p:any)=>`${String(p.symbol||"").replace("-USDT","")} ${String(p.positionSide||"")} · ${n(p.leverage,0)}x · 미실현 ${n(p.unrealizedProfit)} USDT`).join("\n")||"열린 포지션 없음";
 return send(id,`<b>${isB?"🟣 B플랜 · Stage93 ALGO·ADA":"🔵 A플랜 · Stage75 낙폭방어형"}</b>\n자동매매 <b>${state.enabled?"ON":"OFF"} · ${state.test_mode?"TEST":"LIVE"}</b>\n잔고 ${n(a.balance)} · Equity ${n(a.equity)} USDT\n가용 담보 ${n(a.available)} · 미실현 ${n(a.upnl)} USDT\n\n${positions}\n\n${isB?"보조 ALGO·ETH·VET·LINK·DOT·LTC·BNB·ADA · ICP/BCH/UNI 완료봉 수익보호\n실거래 성과 기준 $650 · 주문은 실제 Equity 기준":"BTC·ETH·XRP·TRX·SOL · 격리 3x · 노출 한도 2.24x · 15% 비상손절"}`);
}
if(t==="🟣 B 기록")return pbHistory(id);
if(t==="🟣 B 잔고"){const a=await pbAccount();return send(id,`<b>🟣 B플랜 · 공격형 계정</b>\n\n잔고 <b>${n(a.balance)} USDT</b>\nEquity <b>${n(a.equity)} USDT</b>\n가용 담보 ${n(a.available)} USDT\n미실현 <b>${a.upnl>=0?"+":""}${n(a.upnl)} USDT</b>\n진행 포지션 <b>${a.positions.length}개</b>`)}
if(t==="🟣 B 포지션"){const a=await pbAccount();if(!a.positions.length)return send(id,"<b>🟣 B플랜 · 진행중 포지션</b>\n\n현재 열린 포지션이 없습니다.");return send(id,`<b>🟣 B플랜 · 진행중 포지션 ${a.positions.length}개</b>\n\n`+a.positions.map((p:any)=>`${String(p.symbol||"").replace("-USDT","")} · ${String(p.positionSide||"")}\n진입 ${px(p.avgPrice??p.entryPrice)} · ${n(p.leverage,0)}x\n미실현 ${n(p.unrealizedProfit)} USDT`).join("\n\n"))}
if(t==="🟣 B 시스템"){const{data:x}=await sb.from("plan_b_trading_state").select("*").eq("id","singleton").single();return send(id,`<b>🟣 B플랜 · 공격형 시스템</b>\n\n자동매매 <b>${x?.enabled?"ON":"OFF"} · ${x?.test_mode?"TEST":"LIVE"}</b>\n전략 ${x?.strategy_id||"-"}\n주문 기준: 담보 예약·가용 한도 감액\n5% 여유 · 진입 수량 고정\n검증 ${x?.validation_status||"-"}`)}
if(t==="🔵 A 기록"||t==="📋 기록"||/거래\s*기록|실거래\s*기록|성과|승률/i.test(t))return history(id);
if(t==="🔵 A 잔고"||t==="💰 잔고"||/담보|잔고|equity/i.test(t)){const a=await account(),u=a.upnl;return send(id,`<b>🔵 A플랜 · BingX 계정</b>\n\n잔고        <b>${n(a.balance)} USDT</b>\nEquity      <b>${n(a.equity)} USDT</b>\n사용 담보   ${n(a.used)} USDT\n가용 담보   ${n(a.available)} USDT\n미실현 손익  <b>${u>=0?"+":""}${n(u)} USDT</b>\n\n진행중 포지션  <b>${a.positions.length}개</b>`)}
if(t==="🔵 A 포지션"||t==="📊 포지션"||/진행|포지션|종목/i.test(t)){const a=await account();if(!a.positions.length)return send(id,"<b>🔵 A플랜 · 진행중 포지션</b>\n\n현재 열린 포지션이 없습니다.");const lines=a.positions.map((p:any)=>{const amt=Math.abs(Number(p.positionAmt??p.positionAmount??0)),sh=String(p.positionSide||"").toUpperCase()==="SHORT"||Number(p.positionAmt)<0,up=Number(p.unrealizedProfit||0);return `<b>${String(p.symbol||"").replace("-USDT","")} · ${sh?"SHORT 🔴":"LONG 🟢"}</b>\n진입 ${px(p.avgPrice??p.entryPrice)}  ·  ${n(p.leverage,0)}x\n수량 ${n(amt,6)}\n미실현 <b>${up>=0?"+":""}${n(up)} USDT</b>`});return send(id,`<b>🔵 A플랜 · 진행중 포지션 ${a.positions.length}개</b>\n\n${lines.join("\n\n")}`)}
if(t==="🔵 A 시스템"||t==="🟢 시스템"||/상태|시스템|오류/i.test(t)){const[{data:s},{data:r}]=await Promise.all([sb.from("coin_snapshots").select("updated_at").eq("id","live").limit(1),sb.from("real_trading_state").select("enabled,test_mode,max_concurrent_positions,max_leverage").eq("id","singleton").limit(1)]),hb=s?.[0]?.updated_at,stale=!hb||Date.now()-Date.parse(hb)>180000,x=r?.[0];return send(id,`<b>🔵 A플랜 · 시스템</b>\n\nCollector   <b>${stale?"🔴 정지":"🟢 정상"}</b>\n자동매매    <b>${x?.enabled?"ON":"OFF"} · ${x?.test_mode?"TEST":"LIVE"}</b>\n동시 포지션  ${x?.max_concurrent_positions??"-"}개\n최대 레버리지 ${x?.max_leverage??"-"}x\n\n마지막 확인\n${hb||"없음"}`)}return send(id,"아래 메뉴에서 확인할 항목을 선택해주세요.")}
Deno.serve(async req=>{if(req.method!=="POST")return Response.json({ok:false},{status:405});if(!validWebhookSecret(req.headers.get("x-telegram-bot-api-secret-token"),webhookSecret(BOT,WEBHOOK_SECRET)))return Response.json({ok:false},{status:403});try{const b=await req.json(),m=b?.message,cb=b?.callback_query;if(cb){const id=String(cb.message?.chat?.id||"");if(id!==CHAT)return Response.json({ok:true});await tg("answerCallbackQuery",{callback_query_id:cb.id});const match=String(cb.data||"").match(/^managed:([0-9a-f-]{36})$/i);if(match)await managedTrades(id,match[1]);return Response.json({ok:true,replied:true})}if(!m)return Response.json({ok:true});const id=String(m.chat?.id||"");if(id!==CHAT)return Response.json({ok:true});try{const reply=await answer(id,String(m.text||""));return Response.json({ok:true,replied:true,message_id:reply?.message_id})}catch(e){await send(id,"⚠️ 조회 실패 · 잠시 후 다시 눌러주세요.");return Response.json({ok:false,query_failed:true})}}catch(e){return Response.json({ok:false},{status:500})}});
