import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";
import { createHmac } from "node:crypto";
const URL=Deno.env.get("SUPABASE_URL")!,SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,BOT=Deno.env.get("TELEGRAM_BOT_TOKEN")||"",CHAT="6818439075",BINGX_KEY=Deno.env.get("BINGX_API_KEY")||"",BINGX_SECRET=Deno.env.get("BINGX_SECRET_KEY")||"",COIN_ISSUE_URL="https://minyoullee.github.io/coin-issue-ai/",WEBHOOK_SECRET=Deno.env.get("TELEGRAM_WEBHOOK_SECRET")||"";
const sb=createClient(URL,SERVICE);const keyboard={keyboard:[["🔵 A플랜","🟣 B플랜"],["🔵 A 잔고","🔵 A 포지션"],["🔵 A 기록","🔵 A 시스템"],["🟣 B 잔고","🟣 B 포지션"],["🟣 B 기록","🟣 B 시스템"],["🔗 Coin Issue AI","❓ 도움말"]],resize_keyboard:true,is_persistent:true};
async function tg(method:string,body:any={}){if(!BOT)throw new Error("TELEGRAM_BOT_TOKEN missing");const r=await fetch(`https://api.telegram.org/bot${BOT}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.ok)throw new Error(`Telegram ${j.error_code}: ${j.description}`);return j.result}
async function send(chatId:string,text:string,menu=true){return tg("sendMessage",{chat_id:chatId,text,parse_mode:"HTML",disable_web_page_preview:true,...(menu?{reply_markup:keyboard}:{})})}
async function link(chatId:string){return tg("sendMessage",{chat_id:chatId,text:"<b>Coin Issue AI</b>\n실시간 코인 이슈·트레이딩 대시보드",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"🚀 대시보드 열기",url:COIN_ISSUE_URL}]]}})}
function n(v:any,d=2){const x=Number(v);return Number.isFinite(x)?x.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}):"-"}function px(v:any){const x=Number(v);return Number.isFinite(x)?(x<10?n(x,5):n(x,2)):"-"}function sign(p:any){const q={...p,timestamp:Date.now()},s=Object.keys(q).sort().map(k=>`${k}=${q[k]}`).join("&");return `${s}&signature=${createHmac("sha256",BINGX_SECRET).update(s).digest("hex")}`}
async function bx(path:string,p:any={}){const r=await fetch(`https://open-api.bingx.com${path}?${sign(p)}`,{headers:{"X-BX-APIKEY":BINGX_KEY},signal:AbortSignal.timeout(10000)});const j=await r.json();if(Number(j.code)!==0)throw new Error(`BingX ${j.code}: ${j.msg}`);return j.data}
async function account(){const[a,p]=await Promise.all([bx("/openApi/swap/v3/user/balance",{recvWindow:5000}),bx("/openApi/swap/v2/user/positions",{recvWindow:5000})]);const rows=Array.isArray(a)?a:(Array.isArray(a?.balance)?a.balance:[a?.balance||a||{}]),b=rows.find((x:any)=>String(x?.asset||"").toUpperCase()==="USDT")||rows[0]||{},pr=(Array.isArray(p)?p:(p?.positions||[])).filter((x:any)=>Math.abs(Number(x.positionAmt??x.positionAmount??0))>0);return{balance:+b.balance||0,equity:+b.equity||0,available:+b.availableMargin||0,used:+b.usedMargin||0,upnl:+b.unrealizedProfit||0,positions:pr}}
async function history(id:string){const{data,error}=await sb.from("bingx_trade_history").select("status,realized_pnl_usd,fee_usd").eq("status","closed").not("realized_pnl_usd","is",null).limit(2000);if(error)throw error;const rows=data||[],pnls=rows.map((x:any)=>Number(x.realized_pnl_usd)).filter(Number.isFinite),wins=pnls.filter((x:number)=>x>0),losses=pnls.filter((x:number)=>x<0),closed=pnls.length,winPnl=wins.reduce((a:number,v:number)=>a+v,0),lossPnl=losses.reduce((a:number,v:number)=>a+v,0),fee=rows.reduce((a:number,x:any)=>a+Math.abs(Number(x.fee_usd)||0),0),net=pnls.reduce((a:number,v:number)=>a+v,0),rate=closed?wins.length/closed*100:0,current=100+net;return send(id,`<b>🔵 A플랜 · BingX 실거래 기록</b>\n\n승률        <b>${n(rate,1)}%</b>\n승리        <b>${wins.length}번  +$${n(winPnl)}</b>\n패배        <b>${losses.length}번  -$${n(Math.abs(lossPnl))}</b>\n\n총 수수료   <b>-$${n(fee)}</b>\n실제 순수익 <b>${net>=0?"+":"-"}$${n(Math.abs(net))}</b>\n현재 담보금 <b>$${n(current)}</b> · 시작 $100`)}
async function answer(id:string,text:string){const t=text.trim();if(t==="/start"||t==="❓ 도움말"||t.toLowerCase()==="help")return send(id,"<b>Coin Issue AI · A/B 독립 운영봇</b>\n\n🔵 <b>A플랜</b>  기존 로직 · 기존 BingX 계정/API\n🟣 <b>B플랜</b>  신규 로직 · 별도 BingX 계정/API\n\n각 플랜의 잔고·포지션·기록·시스템 버튼이 완전히 분리됩니다.\n현재 B플랜은 연구 및 전용 API 연결 대기 상태입니다.\n\n진입 · 청산 · 오류 알림에도 플랜명이 표시됩니다.");if(t==="🔗 Coin Issue AI"||/코인\s*이슈|coin issue/i.test(t))return link(id);if(t==="🔵 A플랜")return send(id,"<b>🔵 A플랜</b>\n기존 로직 · 기존 BingX 계정/API · 현재 운영 중\n아래 A 전용 버튼에서 잔고·포지션·기록·시스템을 확인하세요.");if(t==="🟣 B플랜"||t.startsWith("🟣 B "))return send(id,"<b>🟣 B플랜</b>\n신규 연구 통과 및 별도 BingX 계정/API 연결 대기 중입니다.\nA플랜 데이터·주문·기록은 절대 섞이지 않습니다.");
if(t==="🔵 A 기록"||t==="📋 기록"||/거래\s*기록|실거래\s*기록|성과|승률/i.test(t))return history(id);
if(t==="🔵 A 잔고"||t==="💰 잔고"||/담보|잔고|equity/i.test(t)){const a=await account(),u=a.upnl;return send(id,`<b>🔵 A플랜 · BingX 계정</b>\n\n잔고        <b>${n(a.balance)} USDT</b>\nEquity      <b>${n(a.equity)} USDT</b>\n사용 담보   ${n(a.used)} USDT\n가용 담보   ${n(a.available)} USDT\n미실현 손익  <b>${u>=0?"+":""}${n(u)} USDT</b>\n\n진행중 포지션  <b>${a.positions.length}개</b>`)}
if(t==="🔵 A 포지션"||t==="📊 포지션"||/진행|포지션|종목/i.test(t)){const a=await account();if(!a.positions.length)return send(id,"<b>🔵 A플랜 · 진행중 포지션</b>\n\n현재 열린 포지션이 없습니다.");const lines=a.positions.map((p:any)=>{const amt=Math.abs(Number(p.positionAmt??p.positionAmount??0)),sh=String(p.positionSide||"").toUpperCase()==="SHORT"||Number(p.positionAmt)<0,up=Number(p.unrealizedProfit||0);return `<b>${String(p.symbol||"").replace("-USDT","")} · ${sh?"SHORT 🔴":"LONG 🟢"}</b>\n진입 ${px(p.avgPrice??p.entryPrice)}  ·  ${n(p.leverage,0)}x\n수량 ${n(amt,6)}\n미실현 <b>${up>=0?"+":""}${n(up)} USDT</b>`});return send(id,`<b>🔵 A플랜 · 진행중 포지션 ${a.positions.length}개</b>\n\n${lines.join("\n\n")}`)}
if(t==="🔵 A 시스템"||t==="🟢 시스템"||/상태|시스템|오류/i.test(t)){const[{data:s},{data:r}]=await Promise.all([sb.from("coin_snapshots").select("updated_at").eq("id","live").limit(1),sb.from("real_trading_state").select("enabled,test_mode,max_concurrent_positions,max_leverage").eq("id","singleton").limit(1)]),hb=s?.[0]?.updated_at,stale=!hb||Date.now()-Date.parse(hb)>180000,x=r?.[0];return send(id,`<b>🔵 A플랜 · 시스템</b>\n\nCollector   <b>${stale?"🔴 정지":"🟢 정상"}</b>\n자동매매    <b>${x?.enabled?"ON":"OFF"} · ${x?.test_mode?"TEST":"LIVE"}</b>\n동시 포지션  ${x?.max_concurrent_positions??"-"}개\n최대 레버리지 ${x?.max_leverage??"-"}x\n\n마지막 확인\n${hb||"없음"}`)}return send(id,"아래 메뉴에서 확인할 항목을 선택해주세요.")}
Deno.serve(async req=>{if(req.method!=="POST")return Response.json({ok:false},{status:405});if(req.headers.get("x-telegram-bot-api-secret-token")!==WEBHOOK_SECRET)return Response.json({ok:false},{status:403});try{const b=await req.json(),m=b?.message;if(!m)return Response.json({ok:true});const id=String(m.chat?.id||"");if(id!==CHAT)return Response.json({ok:true});try{await answer(id,String(m.text||""))}catch(e){await send(id,`<b>⚠️ 조회 실패</b>\n\n${e instanceof Error?e.message:String(e)}`)}return Response.json({ok:true})}catch(e){return Response.json({ok:false},{status:500})}});

