-- R-Lab is an isolated observation-only system. It has no order, credential,
-- trading-state, or A/B/C mutation path.
create table if not exists public.rlcd_shadow_decisions (
  id bigint generated by default as identity primary key,
  decision_key text not null unique,
  model_version text not null,
  symbol text not null,
  decided_at timestamptz not null,
  horizon_hours integer not null check(horizon_hours in (1,4,24)),
  matures_at timestamptz not null,
  source_snapshot_at timestamptz not null,
  inputs jsonb not null default '{}'::jsonb,
  p_long numeric not null check(p_long between 0 and 1),
  p_short numeric not null check(p_short between 0 and 1),
  p_no_trade numeric not null check(p_no_trade between 0 and 1),
  action text not null check(action in ('long','short','no_trade')),
  confidence numeric not null check(confidence between 0 and 1),
  entry_price numeric not null check(entry_price>0),
  status text not null default 'pending' check(status in ('pending','scored')),
  exit_price numeric,
  gross_return_pct numeric,
  net_return_pct numeric,
  cost_pct numeric,
  mae_pct numeric,
  mfe_pct numeric,
  successful boolean,
  counterfactual jsonb,
  scored_at timestamptz,
  created_at timestamptz not null default now(),
  check(abs((p_long+p_short+p_no_trade)-1)<0.000001)
);
create index if not exists rlcd_shadow_pending_idx on public.rlcd_shadow_decisions(status,matures_at);
create index if not exists rlcd_shadow_calibration_idx on public.rlcd_shadow_decisions(model_version,horizon_hours,status,confidence);
alter table public.rlcd_shadow_decisions enable row level security;
revoke all on public.rlcd_shadow_decisions from public,anon,authenticated;
grant all on public.rlcd_shadow_decisions to service_role;

create or replace view public.rlcd_shadow_calibration as
select model_version,horizon_hours,
       width_bucket(confidence,0,1,10) as confidence_bucket,
       count(*) as samples,avg(confidence) as mean_confidence,
       avg(case when successful then 1 else 0 end) as observed_success_rate,
       avg(power(confidence-(case when successful then 1 else 0 end),2)) as brier_component,
       avg(net_return_pct) as mean_net_return_pct
from public.rlcd_shadow_decisions where status='scored'
group by model_version,horizon_hours,width_bucket(confidence,0,1,10);
revoke all on public.rlcd_shadow_calibration from public,anon,authenticated;
grant select on public.rlcd_shadow_calibration to service_role;

do $$ begin
  if not exists(select 1 from cron.job where jobname='rlcd-shadow-hourly') then
    perform cron.schedule('rlcd-shadow-hourly','7 * * * *',$job$
      select net.http_post(
        url := 'https://ljazcstmwtuhideaarti.supabase.co/functions/v1/rlcd-shadow',
        headers := jsonb_build_object('Content-Type','application/json','apikey','sb_publishable_a-LZ7__bpIa6j8C7Bjdr1Q_aQJJbdVz','x-scheduler-key',(select secret_value->>'key' from public.private_runtime_secrets where id='scheduler_auth')),
        body := jsonb_build_object('scheduled_at',now()),timeout_milliseconds := 50000
      );
    $job$);
  end if;
end $$;
