create table if not exists public.plan_b_trading_state (
  id text primary key default 'singleton',
  enabled boolean not null default false,
  test_mode boolean not null default true,
  strategy_id text not null default 'etc_link_vsr_stage6',
  account_fingerprint text,
  updated_at timestamptz not null default now(),
  constraint plan_b_singleton check (id = 'singleton')
);

create table if not exists public.plan_b_signals (
  id bigint generated by default as identity primary key,
  signal_key text not null unique,
  symbol text not null check (symbol in ('ETC','LINK')),
  side text not null check (side in ('long','short')),
  status text not null default 'active' check (status in ('active','expired','closed','rejected')),
  signal_price numeric not null,
  volume_ratio numeric not null,
  return_1h numeric not null,
  realized_vol_24h numeric not null,
  hold_hours integer not null,
  leverage numeric not null default 3,
  portfolio_weight numeric not null,
  portfolio_scale numeric not null default 1.75,
  confirmed_at timestamptz not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_b_real_trades (
  id bigint generated by default as identity primary key,
  signal_id bigint not null unique references public.plan_b_signals(id),
  symbol text not null,
  side text not null,
  status text not null default 'open' check (status in ('open','closed','rejected')),
  entry_price numeric,
  close_price numeric,
  quantity numeric,
  leverage numeric,
  margin_usd numeric,
  net_pnl_usd numeric,
  fee_usd numeric,
  client_order_id text unique,
  bingx_order_id text,
  reject_reason text,
  signal_confirmed_at timestamptz,
  dispatch_started_at timestamptz,
  exchange_accepted_at timestamptz,
  filled_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.plan_b_trading_state(id,enabled,test_mode)
values ('singleton',false,true)
on conflict (id) do update set enabled=false, test_mode=true, updated_at=now();

alter table public.plan_b_trading_state enable row level security;
alter table public.plan_b_signals enable row level security;
alter table public.plan_b_real_trades enable row level security;
revoke all on public.plan_b_trading_state, public.plan_b_signals, public.plan_b_real_trades from public, anon, authenticated;
grant all on public.plan_b_trading_state, public.plan_b_signals, public.plan_b_real_trades to service_role;
grant usage, select on sequence public.plan_b_signals_id_seq, public.plan_b_real_trades_id_seq to service_role;
