create table if not exists public.trade_control_commands (
  id bigint generated by default as identity primary key,
  command text not null check (command in ('force_mdd30')),
  symbols jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','claimed','consumed')),
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  consumed_at timestamptz
);
alter table public.trade_control_commands enable row level security;
revoke all on table public.trade_control_commands from public, anon, authenticated;
grant select, insert, update on table public.trade_control_commands to service_role;
grant usage, select on sequence public.trade_control_commands_id_seq to service_role;

create or replace function public.claim_trade_control_command()
returns setof public.trade_control_commands
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id bigint;
begin
  select id into v_id from public.trade_control_commands
  where status='pending' order by id for update skip locked limit 1;
  if v_id is null then return; end if;
  return query update public.trade_control_commands
    set status='claimed',claimed_at=now() where id=v_id returning *;
end $$;
revoke all on function public.claim_trade_control_command() from public,anon,authenticated;
grant execute on function public.claim_trade_control_command() to service_role;
