create table if not exists public.trade_execution_trace (
  id bigint generated by default as identity primary key,
  signal_id bigint not null,
  stage text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.trade_execution_trace enable row level security;
revoke all on table public.trade_execution_trace from public, anon, authenticated;
grant select, insert, delete on table public.trade_execution_trace to service_role;
grant usage, select on sequence public.trade_execution_trace_id_seq to service_role;
create index if not exists trade_execution_trace_signal_idx
  on public.trade_execution_trace(signal_id, id);
