begin;

create table public.managed_bingx_accounts (
  id uuid primary key default gen_random_uuid(),
  display_name text not null unique check (char_length(display_name) between 1 and 60),
  assigned_plan text not null check (assigned_plan in ('A','B')),
  starting_equity_usdt numeric(24,8) not null check (starting_equity_usdt > 0),
  current_equity_usdt numeric(24,8) check (current_equity_usdt >= 0),
  status text not null default 'draft' check (status in ('draft','connected','paused','error')),
  live_enabled boolean not null default false,
  alerts_enabled boolean not null default false,
  api_key_secret_id uuid,
  secret_key_secret_id uuid,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint managed_bingx_secret_pair check (
    (api_key_secret_id is null and secret_key_secret_id is null) or
    (api_key_secret_id is not null and secret_key_secret_id is not null)
  ),
  constraint managed_bingx_live_requires_connection check (
    not live_enabled or (status = 'connected' and api_key_secret_id is not null)
  )
);

comment on column public.managed_bingx_accounts.api_key_secret_id is
  'Opaque Supabase Vault secret UUID only. Never store or return the API key itself.';
comment on column public.managed_bingx_accounts.secret_key_secret_id is
  'Opaque Supabase Vault secret UUID only. Never store or return the secret key itself.';

create table public.managed_bingx_trades (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.managed_bingx_accounts(id) on delete restrict,
  assigned_plan text not null check (assigned_plan in ('A','B')),
  symbol text not null check (symbol ~ '^[A-Z0-9]{2,20}$'),
  side text not null check (side in ('long','short')),
  status text not null check (status in ('reserved','open','closing','closed','rejected','unknown')),
  quantity numeric(32,12),
  leverage numeric(10,4),
  margin_usdt numeric(24,8),
  entry_price numeric(32,12),
  close_price numeric(32,12),
  realized_pnl_usdt numeric(24,8),
  fee_usdt numeric(24,8),
  opened_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index managed_bingx_accounts_status_idx
  on public.managed_bingx_accounts(status, display_name);
create index managed_bingx_trades_account_created_idx
  on public.managed_bingx_trades(account_id, created_at desc);
create index managed_bingx_trades_open_idx
  on public.managed_bingx_trades(account_id, status)
  where status in ('reserved','open','closing','unknown');

alter table public.managed_bingx_accounts enable row level security;
alter table public.managed_bingx_trades enable row level security;

revoke all on public.managed_bingx_accounts from public, anon, authenticated;
revoke all on public.managed_bingx_trades from public, anon, authenticated;
grant select, insert, update on public.managed_bingx_accounts to service_role;
grant select, insert, update on public.managed_bingx_trades to service_role;
grant usage, select on sequence public.managed_bingx_trades_id_seq to service_role;

alter table public.dashboard_login_limits drop constraint dashboard_login_limits_plan_check;
alter table public.dashboard_login_limits
  add constraint dashboard_login_limits_plan_check check (plan in ('A','B','M'));

create or replace function public.dashboard_login_attempt(p_plan text,p_key text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare at_time timestamptz:=clock_timestamp(); n integer; until_time timestamptz;
begin
 if p_plan is null or p_plan not in ('A','B','M') or p_key is null or p_key !~ '^[0-9a-f]{64}$' then raise exception 'invalid login bucket'; end if;
 delete from public.dashboard_login_limits where expires_at<at_time-interval '1 day';
 insert into public.dashboard_login_limits as limits(plan,client_hash,attempts,expires_at)
 values(p_plan,p_key,1,at_time+interval '15 minutes')
 on conflict(plan,client_hash) do update set
 attempts=case when limits.expires_at<=at_time then 1 else least(limits.attempts+1,6) end,
 expires_at=case when limits.expires_at<=at_time then at_time+interval '15 minutes' else limits.expires_at end
 returning attempts,expires_at into n,until_time;
 return jsonb_build_object('allowed',n<=5,'retry_after',case when n<=5 then 0 else greatest(1,ceil(extract(epoch from until_time-at_time)))::integer end);
end $$;
revoke all on function public.dashboard_login_attempt(text,text) from public,anon,authenticated;
grant execute on function public.dashboard_login_attempt(text,text) to service_role;

commit;
